extends:
  - airbnb
  - plugin:flowtype/recommended
plugins:
  - react
  - jsx-a11y
  - import
  - flowtype
  - prettier
rules:
  max-len:
    - 2
    - code: 120
      tabWidth: 2
  semi:
    - 2
    - never
  import/prefer-default-export: 0
  import/order:
    - error
    - groups:
        - - builtin
          - external
        - internal
        - - parent
          - sibling
          - index
      newlines-between: always
  no-nested-ternary: 0
  react/prop-types: 0
  react/jsx-filename-extension: 0
  react/require-default-props: 0
  react/sort-comp:
    - 2
    - order:
        - type-annotations
        - static-methods
        - lifecycle
        - everything-else
        - render
